### PR TITLE
Audit Table first finish

### PR DESCRIPTION
**Pull request by dpattermann-usgs**
This is basically my first pass finished product of the audit table. I'm guessing some more work will be done but I think it's an okay starting point. 
What it does
- get logged transactions from `monitoringLocations` api
- put these into a v-data-table
- if there are changes, have an expandable row that lets you look at a table of column, oldvalue, newvalue

### CODE REVIEW

**Comment by dpattermann-usgs** [comment]
Heads up: Now that I added the router in, you're going to need to run npm install before it works again

**Comment by kmschoep-usgs** [comment]
@dpattermann-usgs , Sorry, I didn't confirm before, but it appears that some tests are broken.

**Comment by dpattermann-usgs** [comment]
@kmschoep-usgs No problem, I can fix those quick. I'm so used to the auto-testing in Decap that I totally blanked on tests!

**Comment by kmschoep-usgs** [comment]
awesome.   I put in a tech debt ticket to get running tests part of the CI/CD for MLR.

**Pull request merged**
